spring:
  application:
    name: nterloc-api-gateway
  threads:
    virtual:
      enabled: true
server:
  port: 8761
  tomcat:
    accesslog:
      enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false