server:
  port: 8080

spring:
  application:
    name: domain-1
  threads:
    virtual:
      enabled: true

  thymeleaf:
    prefix: classpath:/sites/admin/templates/
  web:
    resources:
      add-mappings: false

management:
  health:
    cassandra:
      enabled: false
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

graph:
  domainName: domain-1
  storage:
    berkeley:
      directory: target/db/berkeleyje
  index:
    lucene:
      directory: target/db/lucene
  management:
    resource.location: file:///Users/michaelcoddington/Documents/Projects/ntrloc/domain-graph-starter/src/main/resources/org/ntrloc/graph/ui

binary:
  storage:
    strategy: block
    block:
      location: target/storage-temp
      autocreate: true

logging:
  level:
    root: info