package org.ntrloc.graph.db.partition.process;

import java.security.SecureRandom;

// Server-side counterpart to the admin-ui's own diagram-shared/short-id.js -- used only as a
// fallback when a client-proposed key/process id (itself usually generated by that same JS
// helper) turns out to already be taken, see DecisionAdminController.createDecision and
// ProcessAdminController.createDefinition. Prefixed so the result is always a valid XML NCName
// (can't start with a digit) wherever it ends up embedded as an id attribute -- not a security
// token, just a short default for whoever doesn't want to type their own key.
public final class ShortIdGenerator {

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final String HEX = "0123456789abcdef";
    private static final int LENGTH = 7;

    private ShortIdGenerator() {
    }

    public static String generate(String prefix) {
        StringBuilder sb = new StringBuilder(prefix.length() + LENGTH);
        sb.append(prefix);
        for (int i = 0; i < LENGTH; i++) {
            sb.append(HEX.charAt(RANDOM.nextInt(HEX.length())));
        }
        return sb.toString();
    }
}
